import { fmt, getBaseInfo } from '../state';
import type { Settings, SalesDoc, PurchaseDoc, Contact } from '../types';
import type { jsPDF } from 'jspdf';

const ACCENT = '#0f766e';
const MUTED = '#6b7280';
const LINE = '#e5e7eb';

function footer(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(`Generated by Apex ERP · ${new Date().toLocaleDateString()}`, 14, doc.internal.pageSize.getHeight() - 8);
    doc.text(`Page ${i} of ${pages}`, doc.internal.pageSize.getWidth() - 14, doc.internal.pageSize.getHeight() - 8, { align: 'right' });
  }
}

function companyBlock(doc: jsPDF, s: Settings, docTitle: string, y: number) {
  doc.setFillColor(15, 118, 110);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 3, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(17);
  doc.setTextColor(15, 118, 110);
  doc.text(s.company.shortName || s.company.name, 14, y + 6);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(MUTED);
  const lines = [s.company.address, `${s.company.city}, ${s.company.country}`, s.company.phone, s.company.email, s.company.website].filter(Boolean);
  lines.forEach((l, i) => doc.text(l, 14, y + 12 + i * 4.2));
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(ACCENT);
  doc.text(docTitle, doc.internal.pageSize.getWidth() - 14, y + 8, { align: 'right' });
  return y;
}

function infoGrid(doc: jsPDF, pairs: [string, string][], x: number, y: number, colW = 60) {
  let yy = y;
  for (const [k, v] of pairs) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(k.toUpperCase(), x, yy);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(17, 24, 39);
    doc.text(String(v), x + colW, yy);
    yy += 5.4;
  }
  return yy;
}

const titleFor = (doc: SalesDoc | PurchaseDoc) => {
  const map: Record<string, string> = {
    invoice: 'TAX INVOICE', quotation: 'QUOTATION', salesOrder: 'SALES ORDER', creditNote: 'CREDIT NOTE',
    bill: 'SUPPLIER BILL', purchaseOrder: 'PURCHASE ORDER', payment: 'RECEIPT', supplierPayment: 'PAYMENT VOUCHER'
  };
  return map[doc.type] || doc.type.toUpperCase();
};

export async function downloadDocPdf(doc: SalesDoc | PurchaseDoc, party: Contact | undefined, settings: Settings) {
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([import('jspdf'), import('jspdf-autotable')]);
  const pdf = new jsPDF();
  const base = getBaseInfo();
  const isBill = doc.type === 'bill';
  const d = doc as any;
  const sym = doc.currency === settings.baseCurrency ? base.symbol : (doc.currency === 'USD' ? '$' : doc.currency + ' ');
  const amount = (n: number) => fmt(n, sym);
  const rows: (string | number)[][] = [];
  for (const l of doc.lines || []) {
    rows.push([l.productName, l.sku || '', String(l.qty), l.unit || '', amount(l.price), amount(l.qty * l.price)]);
  }
  const totals = [
    ['Subtotal', amount(doc.subtotal || 0)]
  ];
  if (isBill) {
    totals.push(['Freight & Shipping', amount(d.freight || 0)]);
    totals.push(['Customs & Duties', amount(d.customs || 0)]);
  }
  if ((doc as any).tax) totals.push([`Tax (${(doc as any).taxRate || 0}%)`, amount((doc as any).tax || 0)]);
  totals.push(['TOTAL', amount(doc.total || 0)]);
  if (doc.currency !== settings.baseCurrency) totals.push([`In ${settings.baseCurrency}`, fmt(doc.totalUsd || 0)]);

  const y = companyBlock(pdf, settings, titleFor(doc), 14);
  const meta: [string, string][] = [
    ['Document No', doc.number],
    ['Date', doc.date]
  ];
  if (doc.dueDate) meta.push(['Due Date', String(doc.dueDate)]);
  if (doc.type === 'quotation' && d.validUntil) meta.push(['Valid Until', String(d.validUntil)]);
  meta.push(['Status', doc.status]);
  meta.push(['Currency', `${doc.currency}${doc.fxRate ? ` (${doc.fxRate}/USD)` : ''}`]);
  const metaY = infoGrid(pdf, meta, pdf.internal.pageSize.getWidth() - 14 - 95, y + 20, 40);

  let yy = metaY + 4;
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(9);
  pdf.setTextColor(MUTED);
  pdf.text(isBill ? 'BILL FROM' : 'BILL TO', 14, yy);
  pdf.setFontSize(11);
  pdf.setTextColor(17, 24, 39);
  pdf.text(party?.name || d.customerName || d.supplierName, 14, yy + 6);
  if (party?.address) pdf.text(`${party.address}, ${party.city}, ${party.country}`, 14, yy + 12);
  if (party?.email) pdf.text(party.email, 14, yy + 17);

  autoTable(pdf, {
    startY: yy + (party?.address ? 26 : 24),
    head: [['Item', 'SKU', 'Qty', 'Unit', 'Unit Price', 'Amount']],
    body: rows,
    theme: 'grid',
    styles: { fontSize: 8.5, cellPadding: 2.5, textColor: [17, 24, 39], lineColor: [229, 231, 235], lineWidth: 0.3 },
    headStyles: { fillColor: [15, 118, 110], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 2: { halign: 'right' }, 4: { halign: 'right' }, 5: { halign: 'right' } },
    margin: { left: 14, right: 14 }
  });

  let yy2 = (pdf as any).lastAutoTable.finalY + 8;
  const rightX = pdf.internal.pageSize.getWidth() - 14;
  for (const [k, v] of totals) {
    const isTotal = k === 'TOTAL';
    pdf.setFont('helvetica', isTotal ? 'bold' : 'normal');
    pdf.setFontSize(isTotal ? 11 : 9.5);
    pdf.setTextColor(isTotal ? 15 : 17, isTotal ? 118 : 24, isTotal ? 110 : 39);
    pdf.text(String(k), rightX - 52, yy2, { align: 'right' });
    pdf.text(String(v), rightX, yy2, { align: 'right' });
    if (isTotal) { pdf.setDrawColor(ACCENT); pdf.setLineWidth(0.6); pdf.line(rightX - 100, yy2 - 3, rightX, yy2 - 3); }
    yy2 += isTotal ? 8 : 6;
  }

  const note = isBill ? 'Goods received. Thank you for your business.' : 'Thank you for your business. Payment terms per agreement.';
  pdf.setFont('helvetica', 'italic');
  pdf.setFontSize(8.5);
  pdf.setTextColor(MUTED);
  pdf.text(note, 14, Math.min(yy2 + 8, pdf.internal.pageSize.getHeight() - 20));

  pdf.setProperties({ title: `${titleFor(doc)} ${doc.number}` });
  footer(pdf);
  pdf.save(`${doc.number.replace(/[/\\]/g, '-')}.pdf`);
}

export async function downloadReportPdf({ title, sub, head, body }: { title: string; sub: string; head: string[][]; body: (string | number)[][] }) {
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([import('jspdf'), import('jspdf-autotable')]);
  const pdf = new jsPDF();
  const base = getBaseInfo();

  companyBlock(pdf, { company: { shortName: 'Apex Gloves International', name: '', address: '', city: '', country: '', phone: '', email: '', website: '' } } as Settings, 'REPORT', 14);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(14);
  pdf.setTextColor(17, 24, 39);
  pdf.text(title, 14, 40);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(8.5);
  pdf.setTextColor(MUTED);
  pdf.text(sub, 14, 46);

  autoTable(pdf, {
    startY: 52,
    head,
    body,
    theme: 'grid',
    styles: { fontSize: 8.5, cellPadding: 2.5, textColor: [17, 24, 39], lineColor: [229, 231, 235], lineWidth: 0.3 },
    headStyles: { fillColor: [15, 118, 110], textColor: 255, fontStyle: 'bold' },
    didParseCell: (data) => {
      const raw = data.row.raw as (string | number)[];
      const cell = data.cell;
      if (typeof raw[data.column.index] === 'number') cell.styles.halign = 'right';
      const text = raw.filter((c) => typeof c === 'string').join(' ');
      if (/total|TOTAL/.test(text)) cell.styles.fontStyle = 'bold';
    },
    margin: { left: 14, right: 14 }
  });

  const endY = (pdf as any).lastAutoTable.finalY;
  if (endY < pdf.internal.pageSize.getHeight() - 30) {
    pdf.setFont('helvetica', 'italic');
    pdf.setFontSize(8);
    pdf.setTextColor(MUTED);
    pdf.text(`All amounts in ${base.symbol} (reporting currency).`, 14, endY + 8);
  }

  pdf.setProperties({ title });
  footer(pdf);
  pdf.save(`${title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.pdf`);
}
